apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: me
            operator: In
            values:
            - awesome
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: me
            operator: In
            values:
            - foo
  containers:
  - name: with-node-affinity
    image: gcr.io/google_containers/pause:2.0
